"""empty message

Revision ID: bc7817ed6e82
Revises: None
Create Date: 2016-11-12 17:22:20.401960

"""

# revision identifiers, used by Alembic.
revision = 'bc7817ed6e82'
down_revision = None

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('sites')
    op.drop_table('analyses')
    op.drop_table('votes')
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('votes',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('rating', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('time', postgresql.TIME(), autoincrement=False, nullable=False),
    sa.Column('site_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['site_id'], ['sites.id'], name='votes_site_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='votes_pkey')
    )
    op.create_table('analyses',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('negativity', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('time', postgresql.TIME(), autoincrement=False, nullable=False),
    sa.Column('site_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['site_id'], ['sites.id'], name='analyses_site_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='analyses_pkey')
    )
    op.create_table('sites',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('url', sa.VARCHAR(length=128), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name='sites_pkey'),
    sa.UniqueConstraint('url', name='sites_url_key')
    )
    ### end Alembic commands ###
